qiime2/q2-diversity

.travis.yml
q2_diversity/__init__.py
q2_diversity/_beta.py
q2_diversity/tests/test_beta.py

this is needed to confirm that some lower level changes that I'm working on aren't breaking things. 
@ebolyen, could you review this one?

adds basic testing

---

q2_diversity/_beta.py
q2_diversity/workflows/feature_table_to_pcoa.md

ENH: add type annotations

---

q2_diversity/markdown/core_metrics.md
q2_diversity/plugin_setup.py

Depends on qiime2/q2-feature-table#16 and requires a wiki update.

ENH: confirms uniform sampling effort

---

q2_diversity/markdown/core_metrics.md
q2_diversity/plugin_setup.py

Simple modification to match new q2-types formatting
Pair-programmed with @jairideout

MAINT: AlphaDiversity -> SampleData[AlphaDiversity]

---

CHANGELOG.md
q2_diversity/markdown/core_metrics.md
q2_diversity/plugin_setup.py

ENH: Specify Rooted Phylogeny

---

q2_diversity/_alpha.py

pair-programmed with @jakereps

ENH: some edits after running on real-world data

---

q2_diversity/markdown/core_metrics.md

ENH: adds new diversity metrics

---

q2_diversity/__init__.py
q2_diversity/_beta.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_beta.py

Here's an example of the output:

ENH: adds bioenv method, fixes #20

---

q2_diversity/markdown/core_metrics.md

Depends on https://github.com/qiime2/q2-feature-table/pull/45

MAINT: updated rarefy parameter name

---

q2_diversity/_beta/_visualizer.py
q2_diversity/_beta/bioenv_assets/index.html
q2_diversity/tests/test_beta.py

Resolves #56 
As this sits it just filters and alerts the user of what was removed. Should specifying optional categories be added to the functionality?

ENH: Filter zero-variance numerical columns from bioenv

---

q2_diversity/_alpha/_method.py
q2_diversity/_beta/_method.py
q2_diversity/tests/test_alpha.py
q2_diversity/tests/test_beta.py

ENH: Rephrase skbio warnings referring to OTUs

---

q2_diversity/__init__.py
q2_diversity/_beta/__init__.py
q2_diversity/_beta/_visualizer.py
q2_diversity/_beta/beta_correlation_assets/index.html
q2_diversity/plugin_setup.py
q2_diversity/tests/test_beta.py
setup.py

Some example visualizations:
https://dl.dropboxusercontent.com/u/2868868/temp/q2-diversity-97/mantel.qzv
https://dl.dropboxusercontent.com/u/2868868/temp/q2-diversity-97/mantel-extra-metadata.qzv

ENH: adds beta_correlation visualizer

---

q2_diversity/_alpha/_method.py
q2_diversity/_beta/_method.py
q2_diversity/tests/test_alpha.py
q2_diversity/tests/test_beta.py

ENH: Raise useful error message on empty table input

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/tests/test_alpha.py

Addresses #91 (in part, with https://github.com/qiime2/q2-types/pull/116)

BUG: Explicit pandas indexing

---

q2_diversity/_filter.py
q2_diversity/plugin_setup.py

... this is the one I was originally trying to fix.

API: Change the sample_metadata to metadata

---

q2_diversity/_beta/_visualizer.py

Fixes #99 
Not sure if this is the best approach, but it worked for me in my tests.

BUG: `beta_correlation` plots not clearing

---

q2_diversity/plugin_setup.py

MAINT: relaxes type requirement on input tables to diversity metrics

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/tests/test_alpha.py

BUG: Escape single quotes in alpha-group-sig table

---

ci/recipe/meta.yaml
licenses/sklearn.txt
q2_diversity/_beta/_method.py
q2_diversity/_core_metrics.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_beta.py

Resolves #108 
Curious on the parameter descriptions. Since it is straight from sklearn I just ported it over, and mentioned on `core_metrics` that it only applies to the `beta`s.

ENH: Allow beta methods to utilize parallel jobs.

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/_beta/_visualizer.py

Depends on https://github.com/qiime2/q2templates/pull/25

MAINT: update to use `q2templates.df_to_html`

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/_alpha/alpha_rarefaction_assets/index.html
q2_diversity/tests/test_alpha_rarefaction.py

Fixes #140
Also fixed a small bug with the HTML markup in this viz.

BUG: alpha-rarefaction median vs sum

---

setup.py

BLD: adds missing package data

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_alpha_rarefaction.py

Relies on https://github.com/qiime2/q2cli/pull/166

ENH: Allow a set of metrics in `alpha_rarefaction`

---

q2_diversity/_core_metrics.py
q2_diversity/tests/test_core_metrics.py

BUG: Prevent core-metrics-phylo n_jobs>1 error

---

ci/recipe/meta.yaml
q2_diversity/_alpha/_visualizer.py
q2_diversity/_alpha/alpha_correlation_assets/index.html
q2_diversity/_alpha/alpha_correlation_assets/src/init.js
q2_diversity/_alpha/alpha_correlation_assets/src/toolbar.js
q2_diversity/_alpha/alpha_group_significance_assets/index.html
q2_diversity/_alpha/alpha_group_significance_assets/src/data.js
q2_diversity/_alpha/alpha_group_significance_assets/src/init.js
q2_diversity/_alpha/alpha_group_significance_assets/src/render.js
q2_diversity/_alpha/alpha_group_significance_assets/src/toolbar.js
q2_diversity/_alpha/alpha_rarefaction_assets/index.html
q2_diversity/_alpha/alpha_rarefaction_assets/src/init.js
q2_diversity/_alpha/alpha_rarefaction_assets/src/render.js
q2_diversity/_alpha/alpha_rarefaction_assets/src/state.js
q2_diversity/_alpha/alpha_rarefaction_assets/src/toolbar.js
q2_diversity/_beta/_beta_rarefaction.py
q2_diversity/_beta/_visualizer.py
q2_diversity/_beta/bioenv_assets/index.html
q2_diversity/_filter.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_alpha.py
q2_diversity/tests/test_alpha_rarefaction.py
q2_diversity/tests/test_beta.py
q2_diversity/tests/test_beta_rarefaction.py
q2_diversity/tests/test_core_metrics.py
q2_diversity/tests/test_filter.py

See qiime2/qiime2#359 for details.

MAINT: new Metadata updates

---

q2_diversity/_beta/_visualizer.py
q2_diversity/_beta/beta_group_significance_assets/index.html
q2_diversity/tests/test_beta.py

beta-group-sig: added raw distances download

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/_alpha/alpha_group_significance_assets/index.html

`alpha-group-significance`: add raw data download

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/_alpha/alpha_correlation_assets/index.html

`alpha-correlation`: added raw metadata download

---

ci/recipe/meta.yaml

Also to enable qiime2/q2-diversity#162

MAINT: update dependencies

---

q2_diversity/__init__.py
q2_diversity/_beta/__init__.py
q2_diversity/_beta/_beta_correlation.py
q2_diversity/_beta/_visualizer.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_beta_correlation.py

ENH: add beta_correlation pipeline

---

q2_diversity/_beta/_method.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_beta.py

Adding in Aitchison distance as discussed in #207

Aitchison distance

---

q2_diversity/_alpha/alpha_rarefaction_assets/index.html

BUG: Stop truncating long legends

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/_beta/_beta_rarefaction.py
q2_diversity/_beta/_method.py
q2_diversity/_beta/_visualizer.py
q2_diversity/_filter.py
q2_diversity/_procrustes.py
versioneer.py

Numerous minor updates for compliance with flake8 v3.6, as discussed in #415.
Note: flake8 has been disabled in versioneer.py.

Update for flake8 v3.6

---

q2_diversity/_beta/_method.py

BUG: fix unclosed hdf5 handle

---

q2_diversity/_beta/_method.py
q2_diversity/_beta/_visualizer.py
q2_diversity/tests/test_adonis.py

This could also be `'sample-id'` - thoughts?

BUG: adonis, normalize MD header

---

q2_diversity/_beta/adonis_assets/run_adonis.R
q2_diversity/tests/test_adonis.py

support single quotes in md

---

q2_diversity/plugin_setup.py

to fix copy pasta from beta-group-significance

ENH: adonis has a new name in plugin registration

---

q2_diversity/_alpha/_visualizer.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_alpha.py

alpha correlation intersect ids

---

LICENSE
q2_diversity/__init__.py
q2_diversity/_alpha/__init__.py
q2_diversity/_alpha/_method.py
q2_diversity/_alpha/_visualizer.py
q2_diversity/_beta/__init__.py
q2_diversity/_beta/_beta_correlation.py
q2_diversity/_beta/_beta_rarefaction.py
q2_diversity/_beta/_method.py
q2_diversity/_beta/_visualizer.py
q2_diversity/_core_metrics.py
q2_diversity/_filter.py
q2_diversity/_ordination.py
q2_diversity/_procrustes.py
q2_diversity/plugin_setup.py
q2_diversity/tests/__init__.py
q2_diversity/tests/test_adonis.py
q2_diversity/tests/test_alpha.py
q2_diversity/tests/test_alpha_rarefaction.py
q2_diversity/tests/test_beta.py
q2_diversity/tests/test_beta_correlation.py
q2_diversity/tests/test_beta_rarefaction.py
q2_diversity/tests/test_core_metrics.py
q2_diversity/tests/test_filter.py
q2_diversity/tests/test_ordination.py
q2_diversity/tests/test_plugin_setup.py
q2_diversity/tests/test_procrustes.py
setup.py

Updated copyright headers to reflect the current year.

MAINT: Update copyright headers to 2020

---

ci/recipe/meta.yaml

Best guess as to what is happening here:
https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2-diversity/builds/96#L5e2ea6a3:366:371

HACK: pin libopenblas for vegan

---

.gitignore
.travis.yml
ci/recipe/meta.yaml
q2_diversity/_alpha/_method.py
q2_diversity/_core_metrics.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_core_metrics.py

ENH: Wires up core-metrics(-phylo) to use diversity-lib

---

q2_diversity/plugin_setup.py

closes #167 
depends on https://github.com/qiime2/data302/pull/98

IMP: adds skbio alpha div metrics url

---

q2_diversity/_beta/_visualizer.py

ENH: adonis: validate metadata to check for NaNs

---

q2_diversity/plugin_setup.py

closes #310 
Search didn't turn up any other `oulu.fi` URLs.

DOC: fixes broken adonis link

---

q2_diversity/_ordination.py
q2_diversity/plugin_setup.py

This PR introduces a `random_state` parameter to the two dimensionality reduction methods: tSNE and UMAP for better result reproducibility.

ENH: add random_state param in dim reduction methods

---

q2_diversity/_core_metrics.py
q2_diversity/plugin_setup.py

This is useful for metagenomic studies where there's frequently over 1M
counts per sample. As a side note, the non-phylogenetic variant already has this
parameter.

ENH:Add subsample w/replacement in phylo-cm

---

ci/recipe/meta.yaml

Reverts qiime2/q2-diversity#334

Revert "pin: R 4.2.0"

---

q2_diversity/_beta/adonis_assets/run_adonis.R

This PR adds a preliminary code block that will provide an R traceback for errors encountered within this R wrapper.

imp: adding R traceback for better error handling

---

q2_diversity/_examples.py
q2_diversity/plugin_setup.py
q2_diversity/tests/test_alpha.py

This PR is part of our 2022 Hacktoberfest team-wide sprint to add usage examples to all methods in each of our core distribution plugins. The methods examples have been added for are as follows:
```
alpha-group-significance
alpha-correlation
```

ex: adds usage examples for Hacktoberfest
