diversity/workflows/feature_table_to_pcoa.md
This was in place for a demo, but using IPython magic causes a problem when converting to a script. Better to just remove this now since this isn't how we'll handle visualization moving forward ([QIIME2 #21](https://github.com/biocore/qiime2/issues/21)). We can always edit the notebook to visualize there in there future demos that use q2d3.
=> MAINT: removes plotting

.travis.yml, q2_diversity/__init__.py, q2_diversity/_alpha.py, q2_diversity/_beta.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_alpha.py, q2_diversity/tests/test_beta.py
partially address #17 
* Adds beta_group_significance, which supports running anosim and permanova (default) to test for grouping of samples by metadata. Resulting visualization looks like:
* Adds alpha_correlation, which supports running pearson or spearman (default) to test for correlations between alpha diversity and sample metadata. Resulting visualization looks like:
=> adds alpha correlation and beta group significance tests 

.travis.yml, LICENSE, q2_diversity/__init__.py, q2_diversity/_alpha/__init__.py, q2_diversity/_alpha/_method.py, q2_diversity/_alpha/_visualizer.py, q2_diversity/_beta/__init__.py, q2_diversity/_beta/_method.py, q2_diversity/_beta/_visualizer.py, q2_diversity/_core_metrics.py, q2_diversity/_ordination.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_alpha.py, q2_diversity/tests/test_beta.py, q2_diversity/tests/test_ordination.py, setup.py
New date-based versioning scheme is:
- YYYY.M.patch.dev0 for development version (e.g. 2017.2.0.dev0, 2017.2.1.dev0, 2018.10.0.dev0)
- YYYY.M.patch for release version (e.g. 2017.2.0, 2017.2.1, 2018.10.0)
Plugins/interfaces are recommended to specify `qiime2 == YYYY.M.*` in setup.py's `install_requires` to obtain patch releases for a given train release.
The new versioning scheme is PEP 440 compliant.
=> ENH: new date-based versioning; `qiime` -> `qiime2` package rename

q2_diversity/__init__.py, q2_diversity/_filter.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_filter.py
Supports filtering samples based on index or metadata (similar to filtering feature tables).
=> ENH: add filter-distance-matrix method

q2_diversity/plugin_setup.py
URLs are changing quite a bit between QIIME 2 releases. It's better to link to the docs site and describe what tutorial users need to look for, instead of having a broken link in the software that requires a patch release to fix. We can re-introduce specific URLs to the software when URLs are more stable/predictable.
=> MAINT: remove filtering tutorial url from help text

.travis.yml, q2_diversity/_beta/_visualizer.py, q2_diversity/_beta/beta_group_significance_assets/index.html, q2_diversity/plugin_setup.py, q2_diversity/tests/test_beta.py
fixes #50 
[Here's](https://dl.dropboxusercontent.com/u/2868868/temp/unweighted-unifrac-body-site-pairwise-significance.qzv) an example .qzv with the pairwise tests.
I've confirmed that the .qzv looks right when computed with ANOSIM (some of the descriptions of values change), and when it is run without the pairwise tests. 
Pairwise tests are off by default since they can be very slow.
=> ENH: adds optional pairwise beta group significance tests

q2_diversity/tests/test_alpha.py
The framework no longer permits metadata IDs to be integers
=> MAINT: remove obsolete test

q2_diversity/_filter.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_filter.py
This feature replicates the `exclude_ids` feature [recently implemented in q2-feature-table](https://github.com/qiime2/q2-feature-table/pull/112).  When `exclude_ids=True`, the samples with ids matching those satisfying the `metadata` (or optionally the `where` clause on the `metadata`) are excluded from rather than included in the DistanceMatrix that is returned by `_filter`.  `False` by default.
=> ENH: Support for negating distance matrix filtering

q2_diversity/__init__.py, q2_diversity/_core_metrics.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_core_metrics.py
Note to reviewer, please "rebase and merge," I would like to preserve the two logical commits represented in this PR.
---
This PR adds support for running non-phylogenetic `core-metrics`. Note, this changes the existing behavior of `core-metrics`, now removing the `tree` input. 
Fixes #112 
This PR also adds support for returning the rarefied table in both `core-metrics*` methods.
Fixes #126
=> ENH: core-metrics upgrades

q2_diversity/_alpha/_visualizer.py, q2_diversity/_alpha/alpha_rarefaction_assets/index.html, q2_diversity/tests/test_alpha_rarefaction.py
Empty columns are ignored and a warning is displayed in the visualization listing the empty columns.
Fixes #141.
Example:
=> BUG: ignore empty metadata columns

q2_diversity/_alpha/_visualizer.py, q2_diversity/_alpha/alpha_rarefaction_assets/src/init.js, q2_diversity/tests/test_alpha.py, q2_diversity/tests/test_alpha_rarefaction.py
Fixes #174 
---
Note to reviewer, this PR contains two logical commits - please rebase and merge.
The first commit is a bit of housekeeping related to leaking file handles, the second commit actually fixes #174.
=> BUG: Handle metadata cols with spaces in the label (alpha-rare)

q2_diversity/_alpha/_visualizer.py, q2_diversity/_alpha/alpha_rarefaction_assets/index.html, q2_diversity/_alpha/alpha_rarefaction_assets/src/data.js, q2_diversity/_alpha/alpha_rarefaction_assets/src/render.js
Fixes #179 
---
Questions for reviewer(s):
1) What do we think of this style of error bar? I went with simple, but can make quite a few alternatives happen here.
2) The legend symbol for the error bars is not my favorite --- it seems a bit too narrow (hard to click), but, making it wider makes it even harder to know what it does, IMO. I am open to alternatives.
3) Error bars are currently showing the 9%/91% values from the parametric 7-number summary. Should we be doing something else here?
=> ENH: Add error bars to alpha-rarefaction plots

q2_diversity/tests/test_alpha.py
There was a minor change to the error message raised by the framework's Metadata object.
=> MAINT: update unit test error message check

q2_diversity/_alpha/_visualizer.py, q2_diversity/tests/test_alpha.py
Fixes #185 
Note, the QZVs generated with this patch still won't be viewable at q2view until https://github.com/qiime2/q2view/issues/87 is resolved.
=> BUG: Support forward slashes in MDC labels

q2_diversity/__init__.py, q2_diversity/_procrustes.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_procrustes.py
Solves the procrustes problem for two ordination matrices. While we can
support N different matrices as inputs, we can't support varidic
outputs, hence this will be deferred to a later PR when the
functionality is available in the framework.
=> ENH: Add procrustes analysis plugin

q2_diversity/citations.bib, q2_diversity/plugin_setup.py, setup.py
=> ENH: added citations

q2_diversity/_alpha/_visualizer.py, q2_diversity/tests/test_alpha_rarefaction.py
Adds a clear error message when all metadata is filtered out from the table - due to non-categorical data being dropped. 
Resolves #199
=> ENH: Add error message when md is fully filtered

q2_diversity/__init__.py, q2_diversity/_ordination.py, q2_diversity/citations.bib, q2_diversity/plugin_setup.py, q2_diversity/tests/test_ordination.py
Allows users to project descriptors into an existing PCoA matrix
Brief summary of the Pull Request, including any issues it may fix using the GitHub closing syntax:
Adds a new method to project variables into a PCoA matrix. This depends on busywork to update the conda recipe (as the method depends on scikit-bio 0.5.3).
A subsequent q2-emperor PR will allow for users to see these results.
**questions**:
I wondered whether or not I should add an annotation to the PCoAResults type. Namely something like `PCoAResults[Biplot]`. This way this method would output a `PCoAResults[Biplot]` artifact that can only be consumed by `q2-emperor`'s `biplot` method. If reviewers think this makes sense, I'll add the proper changes in q2-types.
=> ENH: Add pcoa biplot method

q2_diversity/_beta/_visualizer.py
Adds permdisp to the beta-group-significance method.
=> ENH: Add permdisp as a group significance method

q2_diversity/_beta/_method.py, q2_diversity/citations.bib, q2_diversity/plugin_setup.py, q2_diversity/tests/test_beta.py
This pull request introduces Canberra-Adkins, which is a normalized variant of the Canberra metric. This metric is more similar, although not identical, to the "Canberra" metric of QIIME1. The slight difference stems from a bug in the QIIME1 implementation in which the number of nonzero elements used in the scaling factor was over estimated. 
Co-authors on this include: @gregcaporaso @antgonza @ElDeveloper @rob-knight and @justin212k following internal discussion. The discrepancy with QIIME1 and QIIME2 was first identified by Dr. Alexey Melnik.
TODO: 
* Is the `ValueError` necessary, or does the `validate=True` in `beta_diversity` assure the values are positive?
=> Canberra Adkins form

q2_diversity/_beta/_visualizer.py
Last week a Qiita user reported an error with Adonis, which turned out to be a problem with its parameters definition, to see the problem:
```
import qiime2 
pm = qiime2.sdk.PluginManager()
adonis = pm.plugins['diversity'].actions['adonis']
In [27]: adonis.signature.parameters['n_jobs']                                                                                                                                                                                                   
Out[27]: ParameterSpec(qiime_type=Int % Range(1, None), view_type=<class 'str'>, default=1, description='Number of parallel processes to run.')
```
If you see we have qiime_type=Int % Range(1, None) but view_type=<class ‘str’>; then if you pass a string to the method, it will raise: “Error running: Parameter …
=> adonis view_type: str->int

ci/recipe/meta.yaml
This PR ups the required version of `unifrac` to expose Faith's PD via `unifrac` in order to trigger QIIME2 continuous integration prior to `q2_alpha_phylogenetic_alt` functionality can be properly tested in #251
=> up unifrac version to expose high performance faith's pd

ci/recipe/meta.yaml, q2_diversity/_beta/_method.py
Resolves #253 which details an extra error check in q2_diversity that should be performed by `unifrac` with the new version requirements. 
I believe I was able to pull out another couple lines corresponding to another check that `unifrac` already performs.
This should result in decreased runtimes on larger datasets.
=> Remove beta phylogenetic extra error check lines

q2_diversity/_core_metrics.py, q2_diversity/plugin_setup.py
This is convenient for the analysis of metabolomic datasets where
subsampling with replacement is time-consuming based on the scale of the
feature counts.
Perhaps this PR should also include an update to `core-metrics-phylogenetic`. I'm happy to add that as long as we think it makes sense.
=> ENH: core-metrics can subsample with replacement

q2_diversity/_beta/_visualizer.py, q2_diversity/_beta/beta_group_significance_assets/index.html
It turns out this does kind of makes sense, it's just super weird.
Many thanks to @angrybee for the [initial legwork here](https://github.com/qiime2/q2-diversity/pull/263#issuecomment-539444693).
=> BUG: fix escaping of filenames in beta-group-sig

q2_diversity/_beta/_method.py, q2_diversity/tests/test_beta.py
This PR just adds another non-phylogenetic metric, Jensen Shannon distance, to the set of non_phylogenetic_metrics. It is one of those additional metrics implemented in [scipy.spatial.distance.pdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html) which can be passed to skbio.diversity.
=> Added jensenshannon metric

ci/recipe/meta.yaml, q2_diversity/__init__.py, q2_diversity/_alpha/__init__.py, q2_diversity/_alpha/_method.py, q2_diversity/_alpha/_visualizer.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_alpha.py, q2_diversity/tests/test_alpha_rarefaction.py
This PR is to transition the `alpha_phylogenetic_alt` method to `alpha_phylogenetic` as the main method for computing Faith's PD with `q2-diversity`. As a reminder, the implementation for the current `alpha_phylogenetic_alt` yields speed improvements and a memory reduction of several orders of magnitude. See [here](https://github.com/biocore/unifrac/pull/65) for more details.
=> Transition alpha_phylogenetic_alt to alpha_phylogenetic

q2_diversity/plugin_setup.py
Bad URL was causing 404 errors. This PR removes duplicated `generated` to align with correct address.
=> BUG: Corrects typo in mantel skbio URL

q2_diversity/_beta/_visualizer.py
=> Bioenv 0 variance filter

q2_diversity/_alpha/_visualizer.py, q2_diversity/_alpha/alpha_rarefaction_assets/src/data.js, q2_diversity/_alpha/alpha_rarefaction_assets/src/render.js, q2_diversity/tests/test_alpha_rarefaction.py
Closes #279. Changes name from `depth` to `_alpha_rarefaction_depth_column_` to mitigate overlap risk.
=> MAINT: Change depth column name

q2_diversity/_beta/_visualizer.py, q2_diversity/tests/test_adonis.py
This is a follow-up PR for https://github.com/qiime2/q2-diversity/pull/282
cc @collin-le & @nbokulich
---
This PR tightens up the NaN checking to _only the columns used in the formula_, rather than raising an error on _any_ column, even if it isn't used.
This changeset also adds a few quick unit tests to exercise this behavior.
=> imp: adonis - tighten scope of nan-checking; tests

q2_diversity/_format.py, q2_diversity/_procrustes.py, q2_diversity/_transformer.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_procrustes.py
@ahdilmore - this PR tweaks the format of the M2 stats a little bit, to make it compatible with QIIME 2 Metadata - this will allow users to "view" the output stats using q2-metadata's `tabulate` visualizer. Basically I transposed the Pandas table, and made the file format into a TSV. I added a new transformer to facilitate viewing as Metadata, and also added some code for validating the format. Would you mind reviewing this and letting me know what you think? Thanks so much! 🦖 
PS - I also cleaned up some parameter description formatting and tacked it into this changeset.
=> imp: m2 fmt validation and metadata-compatible

q2_diversity/_format.py, q2_diversity/_procrustes.py, q2_diversity/plugin_setup.py, q2_diversity/tests/test_procrustes.py
- Adds a permutations parameter.
- Add handling for zero permutations.
- Avoid returning p-value=0 to mimic the behaviour of other
permutation-based tests.
- Rename trials to permutations.
=> ENH: Multiple changes and enhancements

q2_diversity/tests/test_alpha_rarefaction.py
https://pandas.pydata.org/docs/whatsnew/v1.3.0.html#float-result-for-groupby-mean-groupby-median-and-groupby-var
All groupby operations now return floats. Older versions of the `alpha-rarefaction` viz would return a mix of floats and ints, so this seems nicer all around.
=> maint: new pandas groupby api

q2_diversity/_beta/_visualizer.py
In the code, beta correlation `mantel()` in `_visualizer.py` opens an instance of `plt.Figure()` and doesn't close it, consuming memory. Added a line to close the instance and free up memory after saving.
=> Closes `plt.Figure()` after saving mantel test plot to free up memory

q2_diversity/citations.bib, q2_diversity/plugin_setup.py
Our Halko citation is from [arxiv](https://arxiv.org/abs/1007.5510). Looks like it was published in [SIAM](https://epubs.siam.org/doi/epdf/10.1137/100804139) the following year. Is general best practice to move to the peer-reviewed pub when we notice this?
I've been thinking about DOIs a bit lately, so added DOI fields for a few commonly-used resources. I haven't updated the citation keys for those or anything - that's OK, right?
=> Citation updates/DOI adds

ci/recipe/meta.yaml
this PR min pins r-base at 4.2.0 to ensure compatibility across the QIIME 2 ecosystem with R 4.2.0 to accommodate ANCOM-BC, since this is now being wrapped within q2-composition.
=> pin: R 4.2.0
